name: Code Review

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  review-code:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        pip install gpt4all  # Install the GPT4All library

    - name: Set GITHUB_COMMIT_MESSAGE
      id: set_commit_message
      run: echo "GITHUB_COMMIT_MESSAGE=$(git log -1 --pretty=format:%B)" >> $GITHUB_ENV

    - name: Get Pushed Code
      id: get_pushed_code
      run: |
        echo "GITHUB_PUSHED_CODE=$(git show --pretty=format:'%b')" >> $GITHUB_ENV

    - name: Print Environment Variables
      run: |
        echo "Commit Message: $GITHUB_COMMIT_MESSAGE"
        echo "Pushed Code: $GITHUB_PUSHED_CODE"

    - name: Run Your Code Review
      run: python ./gpt4all-code-review/review-code.py
